Merged in bugfix/MTM-39235/downgrade_karaf_to_fix_no_class_issue_10_10 (pull request #1122)
MTM-39235 [BD] Karaf unable to start up unsatisfied dependencies: Dependency on java.lang.NoClassDefFoundError: - downgrade karaf to the one where issue didn't occur but leave jetty version because of vulnerability

* MTM-39235 [BD] Karaf unable to start up unsatisfied dependencies: Dependency on java.lang.NoClassDefFoundError: - downgrade karaf to the one where issue didn't occur but leave jetty version because of vulnerability

Approved-by: Kamil Sobala
Approved-by: Karol Kaczmarski